modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="bc_dimensions"
version="1.0.0"
displayName="Builders Companion Dimensions"
authors="Judicius"
description='''Dimension Companion mod designed for Builders Delight 4.'''

[[dependencies.bc_dimensions]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.bc_dimensions]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

